"""Offline contracts for Flatpak Python manifest generation and budgets."""
import fixtures  # noqa: F401  (must be first: isolates DATA_PATH)

import hashlib
import io
import json
from pathlib import Path
import tarfile
import tempfile
import zipfile

from flatpak.ci import check_python_payload as payload
from flatpak.ci import generate_python_manifest as generator


def check_output_normalization() -> None:
    lock = generator.normalize_lock("requests==2.32.3\n")
    assert lock.startswith("# Generated by flatpak/ci/generate_python_manifest.py")
    manifest = generator.normalize_manifest("# unstable command\nname: dependencies\n")
    assert manifest.splitlines()[0] == generator.MANIFEST_HEADER
    generator.validate_manifest(
        "opencv-python-headless\n"
        "url: https://files.pythonhosted.org/opencv_python_headless-1.whl\n"
    )
    try:
        generator.validate_manifest(
            "opencv-python-headless\n"
            "url: https://files.pythonhosted.org/opencv_python-1.whl\n"
        )
    except ValueError as error:
        assert "full opencv-python" in str(error)
    else:
        raise AssertionError("full OpenCV wheel must fail validation")
    print("PASS: generated output has stable provenance and headless OpenCV")


def check_archive_sizes_and_hashes(directory: Path) -> None:
    wheel = directory / "sample.whl"
    with zipfile.ZipFile(wheel, "w") as archive:
        archive.writestr("one", b"123")
        archive.writestr("two", b"4567")
    assert payload.archive_unpacked_size(wheel, "sample.whl") == 7

    source = directory / "sample.tar.gz"
    with tarfile.open(source, "w:gz") as archive:
        info = tarfile.TarInfo("payload")
        info.size = 5
        archive.addfile(info, io.BytesIO(b"12345"))
    assert payload.archive_unpacked_size(source, "sample.tar.gz") == 5

    digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
    payload.verify_archive(wheel, digest)
    try:
        payload.verify_archive(wheel, "0" * 64)
    except ValueError as error:
        assert "SHA-256 mismatch" in str(error)
    else:
        raise AssertionError("incorrect archive hash must fail")
    print("PASS: archive sizes and SHA-256 checks use archive contents")


def check_architecture_selection() -> None:
    universal = {"type": "file", "url": "universal", "sha256": "a" * 64}
    x86 = {
        "type": "file", "url": "x86", "sha256": "b" * 64,
        "only-arches": ["x86_64"],
    }
    arm = {
        "type": "file", "url": "arm", "sha256": "c" * 64,
        "only-arches": ["aarch64"],
    }
    manifest = {"sources": [universal, x86, arm]}
    assert payload.selected_sources(manifest, "x86_64") == [universal, x86]
    assert payload.selected_sources(manifest, "aarch64") == [universal, arm]
    print("PASS: payload selection is architecture-specific")


def check_budget_policy(directory: Path) -> None:
    assert payload.rounded_budget(100 * payload.MIB, 5) == 105 * payload.MIB
    contract = {
        "metric": "sum-uncompressed-archive-file-bytes",
        "headroom_percent": 5,
        "architectures": {
            "x86_64": {"baseline_bytes": 100, "budget_bytes": payload.MIB},
            "aarch64": {"baseline_bytes": 200, "budget_bytes": payload.MIB},
        },
    }
    path = directory / "budgets.json"
    path.write_text(json.dumps(contract), encoding="utf-8")
    assert payload.load_budget_contract(path) == {
        "x86_64": payload.MIB,
        "aarch64": payload.MIB,
    }
    contract["architectures"]["x86_64"]["budget_bytes"] = 2 * payload.MIB
    path.write_text(json.dumps(contract), encoding="utf-8")
    try:
        payload.load_budget_contract(path)
    except ValueError as error:
        assert "by policy" in str(error)
    else:
        raise AssertionError("budget outside the approved policy must fail")
    assert payload.budget_errors(
        {"x86_64": 11, "aarch64": 9},
        {"x86_64": 10, "aarch64": 10},
    ) == ["x86_64 payload 11 bytes exceeds budget 10 bytes"]
    print("PASS: payload budgets preserve the approved headroom policy")


def main() -> None:
    fixtures.start_watchdog(30, label="scenario_flatpak_python_manifest")
    check_output_normalization()
    check_architecture_selection()
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory)
        check_archive_sizes_and_hashes(path)
        check_budget_policy(path)
    print("PASS: scenario_flatpak_python_manifest")


if __name__ == "__main__":
    main()
