#!/usr/bin/env python3
"""Generate the locked Flatpak Python dependency manifest."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

import yaml


ROOT = Path(__file__).resolve().parents[2]
REQUIREMENTS = ROOT / "requirements.txt"
BUILD_REQUIREMENTS = ROOT / "flatpak" / "requirements-build-tools.txt"
LOCK = ROOT / "flatpak" / "python-requirements.lock"
BUILD_LOCK = ROOT / "flatpak" / "python-build-requirements.lock"
MANIFEST = ROOT / "pypi-requirements.yaml"
MANIFEST_HEADER = (
    "# Generated by flatpak/ci/generate_python_manifest.py from the locked "
    "runtime and build requirements; do not edit."
)
BUILD_TARGET = "${PWD}/.build-tools"
BUILD_ENV = f'PATH="{BUILD_TARGET}/bin:${{PATH}}" PYTHONPATH="{BUILD_TARGET}"'
RUNTIME_ENV = (
    f'PATH="{BUILD_TARGET}/bin:${{PATH}}" '
    f'PYTHONPATH="{BUILD_TARGET}:${{FLATPAK_DEST}}/lib/python3.13/site-packages"'
)


def _run(command: list[str]) -> None:
    try:
        subprocess.run(command, cwd=ROOT, check=True)
    except FileNotFoundError as error:
        raise RuntimeError(f"required command is unavailable: {command[0]}") from error
    except subprocess.CalledProcessError as error:
        raise RuntimeError(f"command failed with exit status {error.returncode}") from error


def normalize_lock(text: str, requirements: Path) -> str:
    source = requirements.relative_to(ROOT)
    header = (
        "# Generated by flatpak/ci/generate_python_manifest.py with Python 3.13 "
        f"from {source}.\n"
        "# Run with --upgrade to select newer transitive dependency versions.\n"
    )
    return header + text.lstrip()


def _command(manifest: dict[str, object], label: str) -> str:
    commands = manifest.get("build-commands")
    if not isinstance(commands, list) or len(commands) != 1 or not isinstance(commands[0], str):
        raise ValueError(f"{label} manifest must contain one build command")
    return commands[0]


def _ignore_installed(command: str) -> str:
    marker = "--exists-action=i"
    if command.count(marker) != 1:
        raise ValueError("generated install command has an unexpected shape")
    return command.replace(marker, f"{marker} --ignore-installed")


def combine_manifests(
    runtime: dict[str, object], build: dict[str, object]
) -> str:
    runtime_command = _ignore_installed(_command(runtime, "runtime"))
    build_command = _ignore_installed(_command(build, "build tool"))
    build_command = build_command.replace(
        "--prefix=${FLATPAK_DEST} --no-build-isolation",
        f"--target={BUILD_TARGET} --no-deps",
    )
    if f"--target={BUILD_TARGET}" not in build_command:
        raise ValueError("could not isolate the generated build-tool command")

    marker = " --no-build-isolation "
    if marker not in runtime_command:
        raise ValueError("runtime command does not disable build isolation")
    install, packages = runtime_command.split(marker, maxsplit=1)
    package_names = packages.split()
    if package_names.count("pycairo") != 1:
        raise ValueError("runtime command must contain pycairo exactly once")
    package_names.remove("pycairo")
    install = f"{install} --no-build-isolation --no-deps"
    pycairo_command = f"{BUILD_ENV} {install} pycairo"
    runtime_command = f"{RUNTIME_ENV} {install} {' '.join(package_names)}"

    sources: list[object] = []
    seen: set[str] = set()
    for manifest in (runtime, build):
        manifest_sources = manifest.get("sources")
        if not isinstance(manifest_sources, list):
            raise ValueError("generated manifest sources must be a list")
        for source in manifest_sources:
            if not isinstance(source, dict) or not isinstance(source.get("sha256"), str):
                raise ValueError("generated manifest source must contain SHA-256")
            digest = source["sha256"]
            if digest not in seen:
                sources.append(source)
                seen.add(digest)

    combined = {
        "name": runtime.get("name"),
        "buildsystem": runtime.get("buildsystem"),
        "build-commands": [f"{BUILD_ENV} {build_command}", pycairo_command, runtime_command],
        "sources": sources,
    }
    return MANIFEST_HEADER + "\n" + yaml.safe_dump(combined, sort_keys=False, width=100)


def validate_manifest(text: str) -> None:
    if "opencv-python-headless" not in text:
        raise ValueError("generated manifest does not install opencv-python-headless")
    for line in text.splitlines():
        if "/opencv_python-" in line:
            raise ValueError("generated manifest selects the full opencv-python wheel")
    if (
        "--target=${PWD}/.build-tools" not in text
        or "--no-deps" not in text
        or text.count("--ignore-installed") != 3
    ):
        raise ValueError("generated manifest does not isolate Python build tools")


def resolve_lock(
    requirements: Path, committed_lock: Path, destination: Path, *, upgrade: bool
) -> str:
    if not upgrade:
        if not committed_lock.is_file():
            raise RuntimeError(f"committed lock is missing: {committed_lock.relative_to(ROOT)}")
        shutil.copyfile(committed_lock, destination)

    command = [
        sys.executable,
        "-m",
        "piptools",
        "compile",
        "--quiet",
        "--no-header",
        "--allow-unsafe",
        "--index-url=https://pypi.org/simple",
        "--no-emit-index-url",
        "--strip-extras",
        f"--output-file={destination}",
    ]
    if upgrade:
        command.append("--upgrade")
    command.append(str(requirements.relative_to(ROOT)))
    _run(command)
    return normalize_lock(destination.read_text(encoding="utf-8"), requirements)


def _generate_partial_manifest(lock_path: Path, destination: Path) -> dict[str, object]:
    _run([
        sys.executable,
        "-m",
        "req2flatpak",
        "--requirements-file",
        str(lock_path),
        "--yaml",
        "--outfile",
        str(destination),
        "--target-platforms",
        "313-aarch64",
        "313-x86_64",
    ])
    data = yaml.safe_load(destination.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("req2flatpak generated an invalid manifest")
    return data


def generate_manifest(runtime_lock: Path, build_lock: Path, directory: Path) -> str:
    runtime = _generate_partial_manifest(runtime_lock, directory / "runtime.yaml")
    build = _generate_partial_manifest(build_lock, directory / "build.yaml")
    text = combine_manifests(runtime, build)
    validate_manifest(text)
    return text


def _check_file(path: Path, expected: str) -> bool:
    try:
        display_path = path.relative_to(ROOT)
    except ValueError:
        display_path = path
    actual = path.read_text(encoding="utf-8") if path.is_file() else ""
    if actual == expected:
        print(f"current: {display_path}")
        return True
    print(f"stale: {display_path}", file=sys.stderr)
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(display_path),
        tofile=f"generated/{display_path}",
        lineterm="",
    )
    for line in diff:
        print(line, file=sys.stderr)
    return False


def generate(*, check: bool, upgrade: bool) -> int:
    if sys.version_info[:2] != (3, 13):
        raise RuntimeError("Flatpak dependency generation requires Python 3.13")
    with tempfile.TemporaryDirectory(prefix="deckard-flatpak-python-") as directory:
        temp = Path(directory)
        lock_path = temp / LOCK.name
        build_lock_path = temp / BUILD_LOCK.name
        lock_text = resolve_lock(REQUIREMENTS, LOCK, lock_path, upgrade=upgrade)
        build_lock_text = resolve_lock(
            BUILD_REQUIREMENTS, BUILD_LOCK, build_lock_path, upgrade=upgrade
        )
        lock_path.write_text(lock_text, encoding="utf-8")
        build_lock_path.write_text(build_lock_text, encoding="utf-8")
        manifest_text = generate_manifest(lock_path, build_lock_path, temp)

    if check:
        return 0 if all((
            _check_file(LOCK, lock_text),
            _check_file(BUILD_LOCK, build_lock_text),
            _check_file(MANIFEST, manifest_text),
        )) else 1
    LOCK.write_text(lock_text, encoding="utf-8")
    BUILD_LOCK.write_text(build_lock_text, encoding="utf-8")
    MANIFEST.write_text(manifest_text, encoding="utf-8")
    print(f"wrote {LOCK.relative_to(ROOT)}")
    print(f"wrote {BUILD_LOCK.relative_to(ROOT)}")
    print(f"wrote {MANIFEST.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    parser.add_argument("--upgrade", action="store_true", help="select newer transitive versions")
    args = parser.parse_args()
    if args.check and args.upgrade:
        parser.error("--check and --upgrade cannot be combined")
    try:
        return generate(check=args.check, upgrade=args.upgrade)
    except (OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
