#!/usr/bin/env python3
"""Generate the locked Flatpak Python dependency manifest."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
REQUIREMENTS = ROOT / "requirements.txt"
LOCK = ROOT / "flatpak" / "python-requirements.lock"
MANIFEST = ROOT / "pypi-requirements.yaml"
LOCK_HEADER = (
    "# Generated by flatpak/ci/generate_python_manifest.py with Python 3.13.\n"
    "# Run with --upgrade to select newer transitive dependency versions.\n"
)
MANIFEST_HEADER = (
    "# Generated by flatpak/ci/generate_python_manifest.py from "
    "flatpak/python-requirements.lock; do not edit."
)


def _run(command: list[str]) -> None:
    try:
        subprocess.run(command, cwd=ROOT, check=True)
    except FileNotFoundError as error:
        raise RuntimeError(f"required command is unavailable: {command[0]}") from error
    except subprocess.CalledProcessError as error:
        raise RuntimeError(f"command failed with exit status {error.returncode}") from error


def normalize_lock(text: str) -> str:
    return LOCK_HEADER + text.lstrip()


def normalize_manifest(text: str) -> str:
    lines = text.splitlines()
    if not lines:
        raise ValueError("req2flatpak generated an empty manifest")
    lines[0] = MANIFEST_HEADER
    return "\n".join(lines) + "\n"


def validate_manifest(text: str) -> None:
    if "opencv-python-headless" not in text:
        raise ValueError("generated manifest does not install opencv-python-headless")
    for line in text.splitlines():
        if "/opencv_python-" in line:
            raise ValueError("generated manifest selects the full opencv-python wheel")


def resolve_lock(destination: Path, *, upgrade: bool) -> str:
    if not upgrade:
        if not LOCK.is_file():
            raise RuntimeError("committed lock is missing; initialize it with --upgrade")
        shutil.copyfile(LOCK, destination)

    command = [
        sys.executable,
        "-m",
        "piptools",
        "compile",
        "--quiet",
        "--no-header",
        "--allow-unsafe",
        "--index-url=https://pypi.org/simple",
        "--no-emit-index-url",
        "--strip-extras",
        f"--output-file={destination}",
    ]
    if upgrade:
        command.append("--upgrade")
    command.append(REQUIREMENTS.name)
    _run(command)
    return normalize_lock(destination.read_text(encoding="utf-8"))


def generate_manifest(lock_path: Path, destination: Path) -> str:
    _run([
        sys.executable,
        "-m",
        "req2flatpak",
        "--requirements-file",
        str(lock_path),
        "--yaml",
        "--outfile",
        str(destination),
        "--target-platforms",
        "313-aarch64",
        "313-x86_64",
    ])
    text = normalize_manifest(destination.read_text(encoding="utf-8"))
    validate_manifest(text)
    return text


def _check_file(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.is_file() else ""
    if actual == expected:
        print(f"current: {path.relative_to(ROOT)}")
        return True
    print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path.relative_to(ROOT)),
        tofile=f"generated/{path.relative_to(ROOT)}",
        lineterm="",
    )
    for line in diff:
        print(line, file=sys.stderr)
    return False


def generate(*, check: bool, upgrade: bool) -> int:
    if sys.version_info[:2] != (3, 13):
        raise RuntimeError("Flatpak dependency generation requires Python 3.13")
    with tempfile.TemporaryDirectory(prefix="deckard-flatpak-python-") as directory:
        temp = Path(directory)
        lock_path = temp / LOCK.name
        lock_text = resolve_lock(lock_path, upgrade=upgrade)
        lock_path.write_text(lock_text, encoding="utf-8")
        manifest_text = generate_manifest(lock_path, temp / MANIFEST.name)

    if check:
        return 0 if all((
            _check_file(LOCK, lock_text),
            _check_file(MANIFEST, manifest_text),
        )) else 1
    LOCK.write_text(lock_text, encoding="utf-8")
    MANIFEST.write_text(manifest_text, encoding="utf-8")
    print(f"wrote {LOCK.relative_to(ROOT)}")
    print(f"wrote {MANIFEST.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    parser.add_argument("--upgrade", action="store_true", help="select newer transitive versions")
    args = parser.parse_args()
    if args.check and args.upgrade:
        parser.error("--check and --upgrade cannot be combined")
    try:
        return generate(check=args.check, upgrade=args.upgrade)
    except (OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
